name: My Dummy Pipeline
on:
  workflow_dispatch:

jobs:
  docker-run:
    name: Create Docker image
    runs-on: ubuntu-latest
    steps:
     # - name: Checkout
     #   uses: actions/checkout@v6.0.1
      - name: Docker build
        run:  |
          docker run -d -p 8080:8080 nginx
          curl http://localhost:8080
