name: Pipeline from my feature branch
on:
  workflow_dispatch:

jobs:
  docker-run:
    name: Create Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Docker build
        run: docker build . -t my-custom-image:01
      - name: Run my custom container
        run: docker run -d my-custom-image:01
